name: hesabdari

services:
  postgres:
    image: postgres:18-alpine
    container_name: hesabdari-postgres
    environment:
      POSTGRES_USER: hesabdari
      POSTGRES_PASSWORD: hesabdari
      POSTGRES_DB: hesabdari
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U hesabdari']
      interval: 5s
      timeout: 5s
      retries: 5

  valkey:
    image: valkey/valkey:8-alpine
    container_name: hesabdari-valkey
    ports:
      - '6379:6379'
    volumes:
      - valkey_data:/data
    healthcheck:
      test: ['CMD', 'valkey-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4.2-management-alpine
    container_name: hesabdari-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: hesabdari
      RABBITMQ_DEFAULT_PASS: hesabdari
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
  valkey_data:
  rabbitmq_data:
